[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bin]]
name = "aoc2023"
bench = false

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
nom = "7"
